#102 Реализовать новое описание действия пользователя
moevm/mse1h2024-moodle pull request #121
Opened 2024-04-16 13:19 UTC by polinaKoroleva05

В таблицу статистики добавлены еще два столбца для более читаемого представления информации о произошедшем событии.

2024-04-16 13:27 UTC, LeraChernyakova approved these changes

2024-04-16 13:28 UTC, DianaRomanenko requested changes

2024-04-16 13:28 UTC, DianaRomanenko commented on client/public/data.json
> +    "group": 9303,
Убери, пожалуйста, номер группы, он вроде уже и в таблице не отображается и с сервера эти данные не будут приходить после того, как PR вольем

2024-04-16 13:49 UTC, polinaKoroleva05 commented on client/public/data.json
> +    "group": 9303,
Готово

2024-04-17 08:34 UTC, DianaRomanenko approved these changes

2024-04-17 08:34 UTC, merged

2024-04-17 12:16 UTC, DianaRomanenko commented
close #112