#117 Изменить формат оправки времени из мудл
moevm/mse1h2024-moodle pull request #124
Opened 2024-04-16 14:09 UTC by defrozentruth

формат времени изменен на ISO-строку (которая включает в себя миллисекунды)

2024-04-16 20:35 UTC, DaniiLBez requested changes

2024-04-16 20:35 UTC, DaniiLBez commented on stat_tracker/moodle_stat_tracker.html
> +                date: `${date.toISOString()}`,
я продолбался в описании задачи. Сервер ждет не строку на вход, а объект типа Date. Не приводи к строке, просто создай таймстемп и отправляй на сервер. Протести локально перед пушем, если запись создастся, тогда все ок, иначе напиши мне, будем смотреть, как править

2024-04-18 18:45 UTC, DianaRomanenko approved these changes

2024-04-20 18:45 UTC, merged

2024-04-21 18:21 UTC, DianaRomanenko commented
resolves #108