#95 Изучить возможность получения данных пользователя из профиля
moevm/mse1h2024-moodle pull request #126
Opened 2024-04-16 16:39 UTC by defrozentruth

добавлены функции извлечения почты и id пользователя на moodle

2024-04-17 12:09 UTC, DianaRomanenko requested changes
Добавь, пожалуйста, соответствующие изменения в readme файл, которые описывают добавленный функционал

2024-04-17 22:26 UTC, defrozentruth commented
> Добавь, пожалуйста, соответствующие изменения в readme файл, которые описывают добавленный функционал

Т.к. данные функции не подразумевают прямого использования пользователем, то данные изменения не требуют отображения в Readme файле с инструкциями по использованию

2024-04-18 08:20 UTC, DianaRomanenko approved these changes

2024-04-18 09:29 UTC, merged

2024-04-21 09:02 UTC, DianaRomanenko commented
resolves #95