#35 Реализовать экспорт отчета
moevm/mse1h2024-moodle pull request #224
Opened 2024-05-08 11:38 UTC by polinaKoroleva05

Создан компонент Dialog, удостоверяющийся, что пользователь хочет скачать статистику, запрашивающий файл csv по url. Открывается проводник для выбора места скачивания.

Ожидает дальнейшей интеграции с серверной частью.

2024-05-15 07:57 UTC, polinaKoroleva05 commented
Отчет по статистике запрашивается с сервера в формате json. 
Отчет по html страницам пока в виде заглушки, т.е может скачивает файл, но из папки public.

2024-05-15 18:02 UTC, DianaRomanenko approved these changes

2024-05-18 10:04 UTC, LeraChernyakova requested changes
Сломалась фильтрация данных. При отправке запроса параметры передавать через {}.

2024-05-18 14:43 UTC, LeraChernyakova approved these changes

2024-05-18 14:44 UTC, merged