#232 Редактирование отображения. Фильтрация и таблица пользователей.
moevm/mse1h2024-moodle pull request #234
Opened 2024-05-12 21:32 UTC by LeraChernyakova

Внесены следующие изменения на клиенте:
- Удалены иконки удаления у администраторов в таблице, где отображаются все пользователи
- Изменено расстояние у кнопок "Поиск" и "Сброс" на страницы отображения статистики
- Изменено имя у кнопки, возвращающей начальный масштаб графика

2024-05-14 21:09 UTC, DianaRomanenko requested changes
При проверке воспроизвелась ошибка со следующим сценарием:
1. Открываю приложение 
2. Перехожу на страницу "Просмотр списка пользователей"
3. У администратора все еще есть кнопка удаления
4. Обновляю страницу и кнопка пропадает 

Скринкаст - https://disk.yandex.ru/i/k_2I9L2hovq71A

2024-05-16 12:02 UTC, polinaKoroleva05 commented
Баг с кнопкой удаления не воспроизвелся

2024-05-16 12:02 UTC, polinaKoroleva05 approved these changes

2024-05-16 12:06 UTC, DianaRomanenko approved these changes

2024-05-16 12:06 UTC, merged