Backend-db-module
moevm/mse1h2024-moodle pull request #50
Opened 2024-03-08 21:29 UTC by DaniiLBez

2024-03-10 07:53 UTC, DianaRomanenko requested changes

2024-03-10 07:53 UTC, DianaRomanenko commented on server/src/core/modules/database/statistic_repo.py
> +    async def get_session(self, record_id: str) -> dict:
Добавить прокидывание ошибки, если сессии нет

2024-03-10 07:53 UTC, DianaRomanenko commented on server/src/models/response.py
> +def error_response_model(error, code, message):
Аналогичный вопрос

2024-03-11 00:29 UTC, DaniiLBez commented
В процессе работы, необходимо собрать, протестировать

2024-03-13 06:01 UTC, DianaRomanenko approved these changes
Слишком большой PR, покрывает далеко не одну задачу. На будущее - так делать не стоит. Одна задача - один PR.

2024-03-13 11:43 UTC, merged