#77 Реализовать треккинг взаимодействия с конкретными элементами moodle
moevm/mse1h2024-moodle pull request #78
Opened 2024-03-23 17:04 UTC by AnjeZenda

2024-03-23 17:07 UTC, AnjeZenda commented
Реализовано отслеживание взаимодействия с такими элементами страницы как ссылки (<a>), поля ввода, текстовые поля ввода и кнопки.

2024-03-23 17:12 UTC, AnjeZenda commented
Обратить внимание на 77 строчку. Возможно необходим согласование типа действия с сервером иначе не будет валидироваться запрос.

2024-03-24 07:16 UTC, DianaRomanenko requested changes
Мы на созвоне обсуждали, что у нас будет три отдельных файла: 
1. Скрипт, с помощью которого будут трекаться все действия 
2. Скрипт, с помощью которого будут трекаться конкретные классы элементов (в рамках текущей задачи)
3. Скрипт, с помощью которого будут трекаться активные страницы 

У тебя все в одном файле сделано, лучше будет разнести на два отдельных
Также в задаче писала, что нужна инструкция по добавлению новых классов трекаемых элементов, добавь отдельный раздел в readme, пожалуйста.

2024-03-24 09:41 UTC, DianaRomanenko approved these changes

2024-03-24 09:41 UTC, merged